name: Release

on:
  push:

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
      
      - name: Install Node Dependencies
        run: npm ci

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      
      - name: Build App Windows
        run: GOOS=windows GOARCH=amd64 go build -o release/wordler-windows-amd64.exe main.go
      
      - name: Build App MacOS Intel
        run: GOOS=darwin GOARCH=amd64 go build -o release/wordler-darwin-amd64 main.go
      
      - name: Build App MacOS Apple Silicon
        run: GOOS=darwin GOARCH=arm64 go build -o release/wordler-darwin-arm64 main.go
      
      - name: Build App Linux
        run: GOOS=linux GOARCH=amd64 go build -o release/wordler-linux-amd64 main.go

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
